name: JSON formatting checker

on:
  push:
    paths:
      - "mac-device-identifiers*.json"
  pull_request:
    paths:
      - "mac-device-identifiers*.json"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Format JSON files
        run: |
          npx jsonlint -i mac-device-identifiers.json
          npx jsonlint -i mac-device-identifiers-unique.json

      - name: Check JSON files have changed
        run: |
          git diff --exit-code --quiet mac-device-identifiers*.json

      - name: Check JSON length is same
        run: |
          length1=`cat mac-device-identifiers.json | jq length`
          length2=`cat mac-device-identifiers-unique.json | jq length`
          test $length1 = $length2
