name: JSON formatting checker

on:
  push:
    paths:
      - "*-device-identifiers*.json"
  pull_request:
    paths:
      - "*-device-identifiers*.json"

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM
        uses: actions/setup-node@v4
        with:
          node-version: 16

      - name: Format JSON files
        run: |
          for file in *.json; do
            npx jsonlint -i "$file"
          done

      - name: Check JSON files have changed
        run: |
          git diff --exit-code --quiet *-device-identifiers*.json

      - name: Check mac-device-identifiers.json is unique
        run: |
          length1=`cat mac-device-identifiers.json | jq length`
          length2=`cat mac-device-identifiers-unique.json | jq length`
          test $length1 = $length2
