name: Scrap from Xcode

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 1' # Every Monday at 00:00 UTC

jobs:
  scrap:
    runs-on: macos-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Check Xcode installation
        run: ls /Applications/Xcode*

      - name: Use latest Xcode
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: latest

      - name: Check Xcode version
        run: |
          xcode-select -p
          xcodebuild -version
          xcodebuild -showsdks

      - name: Install Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x

      - name: Run scrape-from-xcode.ts
        run: |
          deno run --allow-run --allow-read --allow-write scripts/scrape-from-xcode.ts

      - name: Get current date
        id: date
        run: |
          echo "DATE=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
          echo "MONTH_YEAR=$(date +'%b %Y')" >> $GITHUB_OUTPUT

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
          title: "[${{ steps.date.outputs.MONTH_YEAR }}] Update apple device identifiers"
          commit-message: "[${{ steps.date.outputs.DATE }}] Update apple device identifiers"
          branch: scrapping-xcode
